<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>stm</string>
    </array>
    <key>name</key>
    <string>Simple Translation Memory</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>comment.stm</string>
        <key>match</key>
        <string>^@.*$</string>
      </dict>
      <dict>
        <key>name</key>
        <string>string.stm</string>
        <key>match</key>
        <string>^#.*$</string>
      </dict>
      <dict>
        <key>name</key>
        <string>invalid.illegal.stm</string>
        <key>match</key>
        <string>^![^
]*</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>text.stm</string>
    <key>uuid</key>
    <string>ca03e751-04ef-4330-9a6b-9b99aae1c417</string>
  </dict>
</plist>
